/*

This asset is mainly composed of two scripts, "Sound"
and "SoundScript":

SoundObject - A scriptable object containing the information required
to generate a gameObject containing a "SoundScript" and a
customized audioSource on runtime. This object contains some
fields which are directly parsed to the audioSource ("audioClip",
"outputMixer", "audioPriority", "loopAudio") and some fields that
enable additional logic:

    "settings3D" - This field allows instantiating the gameObject as
    a copy of a prefab. This prefab is required to have at least
    an audioSource component for proper functioning. The fields which
    are included in the "Sound" will be overwritten but all the other
    ones will be kept. The idea was that this logic would allow
    easily including consistent 3D settings across different sounds
    (shown in the sample scene). In practice this field can also be 
    used to instantiate the audioSource as part of a complex
    object, albeit this might require additional logic. Leave this
    field empty to generate 2D sounds.

    "dynamicVolume" - This field uses auxiliary code "FloatVariable"
    to allow for dynamic updates to the volume of the audioSources
    after they have been instantiated. This is useful, for example,
    if you wish to allow the player to change the in-game volume.
    You can also leave this field empty to ignore this logic.

    "baseVolume/randomVolume" - The baseVolume is used as the center
    of an uniform distribution with the interval ]-randomVolume/2,
    randomVolume/2]. Bear in mind that Unity clips the volume between
    0 and 1.

    "basePitch/randomPitch" - Same logic as the "baseVolume/randomVolume",
    except Unity only clips the pitch at 0.

    "ignoreTimescale" - If set to false, the "SoundScript" will dynamically
    scale its pitch with the value of Time.timeScale.

SoundScript - A script generated by the sound object in runtime which handles
the dynamic volume and pitch changes, as well as the logic to destroy the 
generated gameObject once its audioSource finishes playing. Non-looping sounds
are destroyed automatically. Looping sounds have to be destroyed from external
calls (stopped from script, destroyed from script, destroyed with parent).

To play an audio clip create a SoundObject from the Unity asset menu and
fill its fields to your liking. Then you can import this object to any script
and call Play() to generate audio at runtime. The Play() function accepts two
optional parameters:

    Transform parent: the generated gameObject is set as a child of the given
    parent.

    Vector3 spawnPosition: the position in which to spawn the gameObject. If
    left as null, the gameObject will either be spawned at parent.position
    or at [0,0,0] if no parent is given.

The Play() function returns a gameObject containing an audioSource and a SoundScript.

The PlayFromUI() function is a wrapper that allows calls from UI elements.

For a practical example on how to use this this asset, please check the
sample scene and the resources available there.

____________________________________________________________________________________________________


                                        Developed by Gingerbad
----------------------------------------------------------------------------------------------------
--------------------------------------------------=++***####*---------------------------------------
-------------------------------------------=+*##%%%%%%#%%%#+----------------------------------------
-------------------------------------=+*#%%%%######%%%%#+-----=-------------------------------------
-------------------------------=+*#%%%%#####%#%%%%%#*=------=#%+------------------------------------
---------------------------=*#%%%%###%#######%%%*+-------=*%%#%%------------------------------------
-----------------------+*#%%#######%######%%#*=------=+#%%%#%##%#-----------------------------------
-------------------=*#%%%%%###%##%%#%%%%#*=------=+#%%#%%#######%*----------------------------------
----------------=*%%%###%%%%%%%%##**+=------=+*#%%##############%%=---------------------------------
--------------=#%%%%%##**++==----------=+*#%%%#%%#####%#%########%%---------------------------------
---------------------------------=+*##%%%##%%#############%###%%%*----------------------------------
-------------------------=++**#%%%%%###%%%#################%%%*=------------==++****######**--------
----------------*#####%%%%%%##%######%######%##########%%%#+=----------*##%%%%%%###%%#####%%--------
-----------------#%##############################%%%%%*+=--------------*%%%#%##########%%%*---------
-----------------=%%#######################%%%%%%#*+-----------------=#%#%##%#######%#%%*-----------
------------------+%%#################%%%%%#**+=-------------------+#%%%###########%%#+-------------
-------------------#%#%########%%%%%%##*+=---------------------=*#%%###########%%%#+----------------
--------------------%%%%%%%%%##**+==-----------------------=+#%%%####%#######%%*+-------------------
---------------------======----------------------------+*#%%%%###%############%#+-------------------
--------------------------------------------------+**#%%############%##########%%#------------------
--------------------------------------------=+*#%%%%#############################%%+----------------
--------------------+----------------=++*#%%%%%########%%####################%%###%%*---------------
----------------=*#%%#+==-===+++*##%%%%%########%%%%%%##%###########################%*--------------
-------------+#%%####%%%%%%%%%%#%%##############+:.  :*%#############################%*-------------
----------+#%%%###%%#####%###%###############%+        %#%###########################%%=------------
-------=*%%%####%#########%#####%##########%%-        -%############################%#%#------------
-----=#%#%%###%%#######%%####%%####%######%%:       :*%##%##########################%##%=-----------
-----%%%%%%%%%%%%%%###%#%########%%%%%%%%#%-       *%###############################%##%*-----------
------=========-+%##%*.+%#%%%%##**++=--%#%+      -%##################################%%%%-----------
---------------#%#%*:  +#%%----------+%%#*      *%#####################################%%-----------
--------------#%#%+    +#%%+=--=*##%%%#%=     .#%%#####################################%%-----------
--------------@%%%     =%%%%%%#%%%#*++-      -%######################################%%%*-----------
--------------@%#%      ...-*%#%+.         .+%%########################################%=-----------
--------------*%%#*.         *%%         .+########################################%##%#------------
---------------*%%%%+:       ##%+.    :=#%#+#%%######################################%%+------------
----------------=#%%%%%#++=+%%###%#*#%%*=.   *##%%###%%##%##########################%%*-------------
-------------------+*%###+++%%##%###%%=      +%#%###%%###%#########################%%#--------------
---------------------%%%+   :#%######%%=.  :+%#%%*-:.-+%%##########################%#---------------
---------------------#%#%=:..+%%%##%%##%%%%#%%#=.      +%##########################%+=--------------
----------------------*%%%%%%###%%########%*-.         *#%#########################%%%#*=-----------
------------------------+*###%%##%%%%#*+-:           -###%#############################%%#*---------
---------------------------=%%%#-.                :+#%###%##########################%%##%%%%*=------
---------------------------+%%%+              :=*%%#######################################%#%%*-----
----------------------------%%#%=      .:-=*#%%###%#########################################%#%#----
----------------------------=#%#%%%###%%%#######%%######%#####################################%%%=--
------------------------------+*#%%%%%%%#**+*#%%%%####%###%%%%%#################################%#--
------------------------------------------------=#%##%%##**+==*%#################################%+-
------------------------------------------------#%##%#------#%%#################################%%%-
-----------------------------------------------#%##%%-----=%%%###################################%@=
----------------------------------------------#%#%%#-----+%#######################################%+
*/